# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/aspnetcore-build:1.0-2.0

options:
  docker: true

pipelines:
  master:
    - step:
        caches:
          - dotnetcore
        script:
          - /bin/bash -c "dotnet restore ./Lunar.Auth.sln && dotnet publish ./Lunar.Auth.sln -c Release"

    - step:
        name: Deployment
        deployment: production
        trigger: manual
        script:
          - export VERSION=0.1.0+$BITBUCKET_COMMIT
          - export IMAGE=$DOCKER_REGISTRY/lunar.auth:$VERSION
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY
          - docker build -f Dockerfile $IMAGE
          - docker push $IMAGE
        services:
          - docker


# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/default-image:latest

# enable Docker for your repository
#options:
#  docker: true
#
#pipelines:
#  default:
#    - step:
#        script: # Modify the commands below to build your repository.
#          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
#          - export IMAGE_NAME=your-Dockerhub-account/your-docker-image-name:$BITBUCKET_COMMIT
#
#          # build the Docker image (this will use the Dockerfile in the root of the repo)
#          - docker build -t $IMAGE_NAME .
#          # authenticate with the Docker Hub registry
#          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
#          # push the new Docker image to the Docker registry
#          - docker push $IMAGE_NAME